### PR TITLE
Use Error::source not Error::cause in Rust versions that have it

### LINKED ISSUE #254: "use of deprecated item 'std::error::Error::cause'" on 2018-12-27 nightly
```
error: use of deprecated item 'std::error::Error::cause': replaced by Error::source, which can support downcasting
   --> src/common.rs:184:1
    |
184 | / error_chain! {
185 | |     foreign_links {
186 | |         Io(::std::io::Error);
187 | |     }
...   |
277 | |     }
278 | | }
    | |_^
    |
```
Expanding it out with `RUSTFLAGS="-Z external-macro-backtrace"` got me
```
error: use of deprecated item 'std::error::Error::cause': replaced by Error::source, which can support downcasting
    |
   ::: <::error_chain::error_chain::error_chain_processing macros>:1:1
    |
1   |           (
    |         __-
    |        |__|
    |       ||__|
    |      |||
2   |      |||  ( {  } , $ b : tt , $ c : tt , $ d : tt ) types $ content : tt $ ( $ tail : tt
3   |      |||  ) * ) => {
4   |      |||  error_chain_processing ! { ( $ content , $ b , $ c , $ d ) $ ( $ tail ) * } }
...        |||
12  |      |||  error_chain_processing ! { ( $ a , $ b , $ content , $ d ) $ ( $ tail ) * } }
    |      |||  --------------------------------------------------------------------------- in this macro invocation (#3)
...        |||
16  |      |||  error_chain_processing ! { ( $ a , $ b , $ c , $ content ) $ ( $ tail ) * } }
    |      |||  --------------------------------------------------------------------------- in this macro invocation (#4)
17  |      |||  ; ( ( $ a : tt , $ b : tt , $ c : tt , $ d : tt ) ) => {
18  |      |||  impl_error_chain_processed ! {
    |  ____|||__-
19  | |    |||  types $ a links $ b foreign_links $ c errors $ d } } ;
    | |    |||                                                   -   -
    | |    |||___________________________________________________|___|
    | |    ||____________________________________________________|___in this expansion of `error_chain_processing!` (#2)
    | |    |_____________________________________________________|___in this expansion of `error_chain_processing!` (#3)
    | |__________________________________________________________|   in this expansion of `error_chain_processing!` (#4)
    |                                                            in this macro invocation (#5)
   --> <::error_chain::error_chain::impl_error_chain_processed macros>:91:40
    |
1   |           ( types {  } $ ( $ rest : tt ) * ) => {
    |      _____-
    |     |_____|
    |    ||_____|
    |   |||
2   |   |||     impl_error_chain_processed ! {
    |   |||_____-
3   |  ||||     types { Error , ErrorKind , ResultExt , Result ; } $ ( $ rest ) * } } ; (
    |  ||||_______________________________________________________________________- in this macro invocation (#6)
4   |   |||     types {
...     |||
7   | / |||     impl_error_chain_processed ! {
8   | | |||     types { $ error_name , $ error_kind_name , $ result_ext_name ; } $ ( $ rest )
9   | | |||     * } /// Convenient wrapper around `std::Result`.
    | |_|||_______- in this macro invocation (#7)
...     |||
91  |   |||     ( ref foreign_err ) => { foreign_err . cause (  ) } ) * _ => None } } } } }
    |   |||                                            ^^^^^
...     |||
154 |   |||     move || { $ crate :: ChainedError :: from_kind ( callback (  ) . into (  ) ) }
155 |   |||     ) } } } ;
    |   |||             -
    |   |||_____________|
    |   ||______________in this expansion of `impl_error_chain_processed!` (#5)
    |   |_______________in this expansion of `impl_error_chain_processed!` (#6)
    |                   in this expansion of `impl_error_chain_processed!` (#7)
    |
   ::: <::error_chain::error_chain::error_chain macros>:1:1
    |
1   |         / ( $ ( $ block_name : ident { $ ( $ block_content : tt ) * } ) * ) => {
2   |         | error_chain_processing ! {
    |  _______|_-
3   | |       | ( {  } , {  } , {  } , {  } ) $ ( $ block_name { $ ( $ block_content ) * } ) *
4   | |       | } } ;
    | |       |_-___- in this expansion of `error_chain!` (#1)
    | |_________|
    |           in this macro invocation (#2)
    |
   ::: src/common.rs:184:1
    |
184 | /         error_chain! {
185 | |             foreign_links {
186 | |                 Io(::std::io::Error);
187 | |             }
...   |
277 | |             }
278 | |         }
    | |_________- in this macro invocation (#1)
```

### PR DESCRIPTION
**Pull request by palfrey**
This should fix #254...

### CODE REVIEW

**Comment by chachi** [comment]
@Yamakaky Any chance this could be merged and the version updated? (Apologies if you're not the one to ping here)

**Comment by palfrey** [comment]
@alexcrichton Any thoughts on this one?

**Comment by alexcrichton** [comment]
Sorry but I don't maintain this crate

File: src/error_chain.rs [hunk 1]
```diff
@@ -188,7 +188,12 @@ macro_rules! impl_error_chain_processed {
                             $(
                                 $(#[$meta_foreign_links])*
                                 $error_kind_name::$foreign_link_variant(ref foreign_err) => {
-                                    foreign_err.cause()
+                                    match () {
```
Comment (hcpl) [inline src/error_chain.rs]: `match` here is unnecessary, can be replaced with
```rust
                                    #[cfg(not(has_error_source))]
                                    {
                                        foreign_err.cause()
                                    }
                                    #[cfg(has_error_source)]
                                    {
                                        foreign_err.source()
                                    }
```

File: src/lib.rs [hunk 2]
```diff
@@ -570,7 +570,12 @@ impl<'a> Iterator for Iter<'a> {
     fn next<'b>(&'b mut self) -> Option<&'a error::Error> {
         match self.0.take() {
             Some(e) => {
-                self.0 = e.cause();
+                self.0 = match () {
```
Comment (hcpl) [inline src/lib.rs]: Same as above
```rust
                self.0 = {
                    #[cfg(not(has_error_source))]
                    {
                        e.cause()
                    }
                    #[cfg(has_error_source)]
                    {
                        e.source()
                    }
                };
```

File: Cargo.toml [hunk 3]
```diff
@@ -21,6 +21,10 @@ travis-ci = { repository = "rust-lang-nursery/error-chain" }
 [features]
 default = ["backtrace", "example_generated"]
 example_generated = []
+has_error_source = [] # Determined by build.rs
```
[the remark this answers is not in the document]
Comment (palfrey) [reply Cargo.toml]: Fixed

File: tests/tests.rs [hunk 4]
```diff
@@ -342,21 +342,34 @@ mod foreign_link_test {
...
         assert_eq!(format!("{}", ForeignError { cause: ForeignErrorCause {} }),
                    format!("{}", error_iter.next().unwrap()));
-        assert_eq!(format!("{}", ForeignErrorCause {}),
-                   format!("{}", error_iter.next().unwrap()));
+        match () {
+            #[cfg(not(has_error_source))]
+            () => assert_eq!(format!("{}", ForeignErrorCause {}),
+                             format!("{}", error_iter.next().unwrap())),
+            #[cfg(has_error_source)]
+            () => assert!(error_iter.next().is_none()),
```
[the remark this answers is not in the document]
Comment (palfrey) [reply tests/tests.rs]: Fixed

File: build.rs [hunk 5]
```diff
@@ -0,0 +1,15 @@
...
+
+use version_check::{is_min_date, is_min_version, is_nightly};
+
+fn main() {
+    // Switch on for versions that have Error::source
+    // As introduced by https://github.com/rust-lang/rust/pull/53533
+    if (is_nightly().unwrap_or(false)
+            && is_min_date("2018-09-02")
+                .unwrap_or((false, "".to_string())).0)
+        || is_min_version("1.30").unwrap_or((false, "".to_string())).0
```
[the remark this answers is not in the document]
Comment (palfrey) [reply build.rs]: Fixed

File: tests/tests.rs [hunk 6]
```diff
@@ -342,21 +342,34 @@ mod foreign_link_test {
...
         let chained_error = try_foreign_error().err().unwrap();
         assert_eq!(format!("{}", ForeignErrorCause {}),
                    format!("{}", ::std::error::Error::cause(&chained_error).unwrap()));
     }
 
+    #[test]
+    #[cfg(has_error_source)]
+    fn finds_source() {
+        let chained_error = try_foreign_error().err().unwrap();
+        assert!(::std::error::Error::source(&chained_error).is_none());
```
[the remark this answers is not in the document]
Comment (palfrey) [reply tests/tests.rs]: That would be what I thought as well, but it doesn't. I've tried experimenting around with this, and can't think what's missing/wrong here (guessed ForeignError was missing something, but adding a `source` method to it didn't help)

File: tests/tests.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (palfrey) [reply tests/tests.rs]: Doing this change broke 1.10 support, so reverting back to my original changes.

[the remark this answers is not in the document]
Comment (hcpl) [reply tests/tests.rs]: My bad, attributes on statements is a [1.13.0](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1130-2016-11-10) feature, should have checked minimal supported Rust first.

And just in case I wasn't clear, here I was referring to the assert for `#[cfg(has_error_source)]` being functionally equal to its `#[cfg(not(has_error_source))]` counterpart above.

File: tests/tests.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (hcpl) [reply tests/tests.rs]: So adding a `source` implementation here didn't work?
https://github.com/rust-lang-nursery/error-chain/blob/38f23249992baadf9c8edbdb07cc45c03d624dbc/src/error_chain.rs#L177-L199
I think it should be exactly the same as the body of `cause` method.

[the remark this answers is not in the document]
Comment (palfrey) [reply tests/tests.rs]: Ah, nice! I'd only added in the tests, but adding it both here and in the tests works and I've been able to get rid of a bunch of the special cases. Thanks! Good catch!

**Comment by palfrey** [comment]
@brson Can you help here?

**Comment by vityafx** [comment]
> Sorry but I don't maintain this crate

But you are listed as an author of the crate. Should not "authors" mean you also maintain this crate? Otherwise, what's the sense in this?

**Comment by brson** [comment]
@palfrey I do not have write access to this repo, and probably no longer have publish permissions. I would merge if I could.

**Comment by brson** [comment]
I posted to users.rlo mentioning that this crate is unmaintained: https://users.rust-lang.org/t/error-chain-is-no-longer-maintained/27561

**Comment by tworec** [comment]
gentelman, can somebody with write access look at this?
@Yamakaky @tailhook @colin-kiegel

File: src/lib.rs (hunk 2 above)
Comment (AndyGauge) [reply src/lib.rs]: This review comment still hasn't been resolved.

File: src/error_chain.rs (hunk 1 above)
Comment (tworec) [reply src/error_chain.rs]: this approach with custom cfg flag will not work in dependent code since there will be not such flag defined and compilation will fail

File: src/lib.rs (hunk 2 above)
Comment (tworec) [reply src/lib.rs]: same as above

File: src/error_chain.rs (hunk 1 above)
Comment (tworec) [reply src/error_chain.rs]: thats what we addressed with @prekucki in last commits here

Comment (tworec) [reply src/error_chain.rs]: @hcpl pls reply

Comment (hcpl) [reply src/error_chain.rs]: Sorry, I thought that my involvement here would be unnecessary because the review comment became outdated. And yes, I forgot that in my solution the flag is processed after `error-chain` has been compiled and the macro has been expanded, my bad.

Do I need to do anything now?

**Comment by colin-kiegel** [comment]
I don't have write access and was also barely involved. I'm sorry I cannot help you here.

File: src/error_chain.rs (hunk 1 above)
Comment (tworec) [reply src/error_chain.rs]: so pls resolve commend below

File: src/lib.rs (hunk 2 above)
Comment (tworec) [reply src/lib.rs]: @AndyGauge do you have write access to this repo?

File: src/error_chain.rs (hunk 1 above)
Comment (hcpl) [reply src/error_chain.rs]: I can't find how I can do that. Someone with write access will be needed for that, perhaps?

Also I thought the comment not being resolved wouldn't block the PR from getting merged since I don't have write access to make that happen (the merge indicator at the bottom of this PR is green which signifies that).

Comment (tworec) [reply src/error_chain.rs]: yup, you're right. txt for replies ;)

**Comment by Yamakaky** [comment]
I no longer have the time to manage error-chain. I'm trying to contact the rust libs team to pass the leadership for this crate.
I also would recommend to use `failure` instead.

**Comment by tworec** [comment]
@Yamakaky thx for your reply. does any1 else have write access to this repo?

File: src/lib.rs (hunk 2 above)
Comment (AndyGauge) [reply src/lib.rs]: @tworec I asked @kodraus on the libs team for write access for this PR.  I'm hoping this ping catches his attention.

Comment (KodrAus) [reply src/lib.rs]: Ah thanks for the ping! @AndyGauge I’ve added you as a collaborator to this repo.

**Comment by AndyGauge** [comment]
@tworec @palfrey @hcpl 
Thank you so much for sorting this out!

**Comment by tworec** [comment]
@AndyGauge do you have also the ability to push to crates.io?

**Comment by palfrey** [comment]
@tworec See #259
