### PR TITLE
example for Backtrace::frames

### LINKED ISSUE #171: Add example for Backtrace::frames

### PR DESCRIPTION
**Pull request by AndyGauge**
Fixes #171

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -461,6 +461,44 @@
...
+//! #       }
+//! #   }
+//! # }
+//! # use errors::*;
+//! fn run() {
+//!    if let Err(ref e) = open_file() {
+//!        if let Some(backtrace) = e.backtrace() {
+//!            let frames = backtrace.frames();
+//!            for (_, frame) in frames.iter().enumerate() {
+//!                for (_, symbol) in frame.symbols().iter().enumerate() {
```
Comment (Yamakaky) [inline src/lib.rs]: Why enumerate?

**Comment by Yamakaky** [comment]
Seems good, thanks!
